#!/bin/bash

# shell process to go into each folder in the watchlist
# and push it to corresponding repo.
usage(){
    echo "Usage:"
    echo " push [course]: push current works to repo"
    echo " pull [course]: update current workspaces"
}

CURRENT=`pwd`
BASE_DIR="/Users/yufanlu/Documents/MSCF"
WATCHLIST="${HOME}/dotfiles/watchlist"

COMMIT_MSG="to be committed"
HAS_CHANGE_MSG="not staged for commit"

#if the number of input is not 1, 2 nor 3, display usage
if [ ${#} -ne 1 -a ${#} -ne 2 ]; then
    usage
    exit 1
elif [ ${#} -eq 1 ]; then
    if [ ${1} = "push" ]; then
        for FOLDER in `cat ${WATCHLIST}`; do
            REPO=${BASE_DIR}/${FOLDER}
            echo "Check repo: ${FOLDER}"
            if [ -d "${REPO}" ]; then
                cd ${REPO}
                HAS_CHANGE=`git status | egrep "${HAS_CHANGE_MSG}"`
                HAS_UNCOMIT=`git status | egrep "${COMMIT_MSG}"`
                if [ "${HAS_CHANGE}" != "" ]; then
                    echo  "${FOLDER}: has unstaged change(s)"
                elif [ "${HAS_UNCOMIT}" != "" ]; then
                    echo  "${FOLDER}: has uncommited change(s)"
                else
                    echo  "${FOLDER}: is clean"
                    git push origin master
                fi
                echo
            fi
        done;
        cd ${CURRENT}
    elif [ ${1} = "pull" ]; then
        for FOLDER in `cat ${WATCHLIST}`; do
            REPO=${BASE_DIR}/${FOLDER}
            echo "Update repo: ${FOLDER}"
            if [ -d "${REPO}" ]; then
                cd ${REPO}
                git pull
                echo
            fi
        done;
        cd ${CURRENT}
    else
        usage
        exit 1
    fi
elif [ ${#} -eq 2 ]; then
    if [ ${1} = "push" ]; then
        for FOLDER in `cat ${WATCHLIST}`; do
            CHECK=`echo ${FOLDER} | egrep "${2}"`
            if [ "${CHECK}" != "" ]; then
                echo "Push changes in repo: ${FOLDER}"
                cd "${BASE_DIR}/${FOLDER}"
                git push
            fi
        done
        cd ${CURRENT}
    elif [ ${1} = "pull" ]; then
        for FOLDER in `cat ${WATCHLIST}`; do
            CHECK=`echo ${FOLDER} | egrep "${2}"`
            if [ "${CHECK}" != "" ]; then
                echo "Update repo: ${FOLDER}"
                cd "${BASE_DIR}/${FOLDER}"
                git pull
            fi
        done
        cd ${CURRENT}
    else
        usage
        exit 1
    fi
fi


